Repository FESI5-team9/Frontend, pull requests merged in 2024-11, with the labels that each got.

#1 feat: Setting
  .eslintrc.json
  .github/pull_request_template.md
  .husky/prepare-commit-msg
  .prettierrc.js
  package-lock.json
  package.json
  tsconfig.json
Labels: :package: CHORE, :sparkles: FEATURE

#2 Dev 브런치 생성
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .husky/prepare-commit-msg
Labels: :sparkles: FEATURE

#3 [MMM-1] folder구조 생성
  public/fonts/next.svg
  public/icons/next.svg
  public/images/vercel.svg
  src/apis/testApi.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/(sign)/layout.tsx
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/favicon.ico
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/layout.tsx
  src/app/myFavorite/gathering/page.tsx
  src/app/myFavorite/layout.tsx
  src/app/myFavorite/myGathering/page.tsx
  src/app/myFavorite/review/page.tsx
  src/app/page.tsx
  src/app/reviews/layout.tsx
  src/app/reviews/page.tsx
  src/components/test.tsx
  src/hooks/usetest.tsx
  src/store/testStore.tsx
  src/types/api/api.d.ts
  src/types/product/product.d.ts
  src/utils/schema.ts
Labels: :package: CHORE

#4 [MNM-17]feat: 공용컴포넌트 모달,팝업 구현
  src/app/(testPages)/modal/page.tsx
  src/app/globals.css
  src/components/Modal.tsx
  src/components/Popup.tsx
  src/components/test.tsx
  src/types/components/modalPopup.d.ts
Labels: :sparkles: FEATURE

#5 [MNM-22]chore: tailwind setting
  tailwind.config.ts
Labels: :package: CHORE

#8 [MNM-27]chore: post-commit husky 추가
  .husky/post-commit
Labels: :package: CHORE

#6 [MNM-21]feat: api통신 함수구현(get,post&put,delete)
  src/apis/method/delete.ts
  src/apis/method/get.ts
  src/apis/method/postPut.ts
Labels: :sparkles: FEATURE

#9 [MNM-25]feat: 프로그레스바기능구현
  package-lock.json
  package.json
  src/app/(testPages)/progressbar/page.tsx
  src/components/Progressbar.tsx
Labels: :sparkles: FEATURE

#10 [MNM-24] feat: input 추가
  package-lock.json
  package.json
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/app/(testPages)/input/page.tsx
  src/app/globals.css
  src/components/Input/Input.tsx
  src/components/Input/TextArea.tsx
  src/utils/schema.ts
Labels: :sparkles: FEATURE

#13 [MNM-23] feat: 공통컴포넌트 filter 구현
  public/images/arrow_drop_down.png
  public/images/swap_vert.png
  src/app/(testPages)/filter/page.tsx
  src/components/FilterDropDown.tsx
  src/constants/filter.ts
  src/types/components/flter.d.ts
Labels: :sparkles: FEATURE

#14 [MNM-34]remove: husky post 삭제
  .husky/post-commit
Labels: :fire:REMOVE

#15 [MNM-28]feat: chip,formatTokoreaTime구현
  package-lock.json
  package.json
  src/app/(testPages)/date/page.tsx
  src/app/(testPages)/progressbar/page.tsx
  src/components/chip.tsx
  src/types/components/chip.d.ts
  src/utils/date.ts
  tailwind.config.ts
Labels: :sparkles: FEATURE, :lipstick: STYLE

#16 [MNM-31]feat: sign 레이아웃 작성
  .husky/post-commit
  public/icons/Ic-Google.svg
  public/icons/Ic-Kakao.svg
  public/icons/google.svg
  public/icons/kakao.svg
  public/images/img_login.png
  src/app/(sign)/layout.tsx
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
Labels: :sparkles: FEATURE

#21 [MNM-33]feat: 회원가입 input 작성
  src/app/(sign)/signup/page.tsx
Labels: :sparkles: FEATURE

#22 [MNM-18] refactor: GNB 수정 반영
  src/app/layout.tsx
  src/components/Gnb.tsx
Labels: :recycle: REFACTOR

#17 [MNM-2] feat: button
  .eslintrc.json
  .prettierrc.js
  src/app/(testPages)/button/page.tsx
  src/components/Button/Button.tsx
  src/components/Button/LinkButton.tsx
  src/components/Button/buttonStyles.ts
  src/types/components/button.d.ts
Labels: :sparkles: FEATURE

#24 [MNM-37]refactor: tailwind config 수정
  tailwind.config.ts
Labels: :recycle: REFACTOR
