Repository FESI5-team9/Frontend, pull requests merged in 2024-12, with the labels that each got.

#26 [MNM-39] refactor: button
  src/app/(testPages)/button/page.tsx
  src/components/Button/Button.tsx
  src/components/Button/LinkButton.tsx
  src/components/Button/buttonStyles.ts
  src/types/components/button.d.ts
  tailwind.config.ts
Labels: :recycle: REFACTOR, :sparkles: FEATURE, :lipstick: STYLE

#27 [MNM-42]feat: API Instance 로직 구성
  .gitignore
  next.config.mjs
  src/apis/ApiError.ts
  src/apis/HttpClient/HttpClient.ts
  src/apis/HttpClient/error.ts
  src/apis/HttpClient/retry.ts
  src/apis/fetchInstance.ts
  src/apis/testApi.tsx
  src/types/api/api.d.ts
  src/types/api/httpClient.d.ts
Labels: :sparkles: FEATURE

#28 [MNM-44]feat: authApi 및 타입 작성
  .gitignore
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/app/(testPages)/(apis)/auth/page.tsx
  src/types/api/authApi.d.ts
Labels: :sparkles: FEATURE

#29 [MNM-46]feat: reviewsApi
  src/apis/reviewsApi.ts
  src/app/(testPages)/(apis)/testReview/page.tsx
  src/types/api/reviews.d.ts
Labels: :sparkles: FEATURE

#30 [MNM-45]feat: gatheringApi 및 타입 작성
  next.config.mjs
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/apis/gatheringsApi.ts
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/types/api/gatheringApi.d.ts
  src/types/api/httpClient.d.ts
Labels: :sparkles: FEATURE

#31 [MNM-43]refactor:api type 및 스웨거 변경사항수정
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/apis/gatheringsApi.ts
  src/apis/reviewsApi.ts
  src/app/(testPages)/(apis)/testgathering/page.tsx
Labels: :recycle: REFACTOR

#32 [MNM-47]feat:intercepter
  src/apis/ApiError.ts
  src/apis/HttpClient/HttpClient.ts
  src/apis/HttpClient/error.ts
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/app/actions/auth.ts
Labels: :recycle: REFACTOR, :sparkles: FEATURE

#34 [MNM-57]refactor: button
  src/app/(testPages)/button/page.tsx
  src/app/(testPages)/date/page.tsx
  src/components/Button/Button.tsx
  src/components/Button/LinkButton.tsx
  src/components/Button/buttonStyles.ts
  src/types/components/button.d.ts
Labels: :recycle: REFACTOR

#36 [MNM-38]refactor sign
  public/icons/X.svg
  public/icons/google.svg
  public/icons/kakao.svg
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
Labels: :recycle: REFACTOR

#37 [MNM-59] refactor: popup
  src/app/(sign)/signin/page.tsx
  src/app/(sign)/signup/page.tsx
  src/app/(testPages)/modal/page.tsx
  src/components/Popup.tsx
  src/types/components/modalPopup.d.ts
Labels: :bug: FIX, :recycle: REFACTOR

#40 [MNM-62] refactor: api
  src/apis/assignGatheringApi.ts
  src/apis/favoriteGatheringApi.ts
  src/apis/searchGatheringApi.ts
  src/app/(home)/[id]/page.tsx
  src/app/(home)/_components/Gathering.tsx
  src/app/(home)/layout.tsx
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/types/api/authApi.d.ts
  src/types/api/gatheringApi.d.ts
  src/types/api/reviews.d.ts
  src/types/components/card.d.ts
Labels: :recycle: REFACTOR

#45 [MNM-41] feat: detailpage 레이아웃 작업
  public/images/checked.svg
  public/images/detailPage/checked.svg
  public/images/detailPage/location.svg
  public/images/heart/empty_heart.svg
  public/images/heart/filled_heart.svg
  public/images/heart/grey_heart.svg
  public/images/image.png
  public/images/location.svg
  src/app/(home)/_components/CreateClub.tsx
  src/app/(home)/_components/FilterSection.tsx
  src/app/(testPages)/calendar/dropdown/page.tsx
  src/app/(testPages)/calendar/page.tsx
  src/app/(testPages)/filter/page.tsx
  src/app/globals.css
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/DetailCard.tsx
  src/app/groupDetail/_components/Map.tsx
  src/app/groupDetail/_components/Reviews.tsx
  src/components/Button/FavoriteButton.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DropdownCalendar.tsx
  src/components/Filter/Dropdown.tsx
  src/components/Filter/FilterButton.tsx
  src/components/Filter/FilterDropDown.tsx
  src/store/dateStore.ts
  src/types/components/button.d.ts
  src/types/components/calendar.d.ts
  src/types/components/filter.d.ts
  src/types/store/date.d.ts
Labels: :sparkles: FEATURE, :lipstick: STYLE

#46 [MNM-64]refactor: API 함수 추가 및 타입 수정, 서버컴포넌트 동작확인
  src/apis/ApiError.ts
  src/apis/HttpClient/HttpClient.ts
  src/apis/authApi.ts
  src/apis/favoriteGatheringApi.ts
  src/apis/fetchInstance.ts
  src/apis/reviewsApi.ts
  src/apis/searchGatheringApi.ts
  src/app/(home)/_components/FilterSection.tsx
  src/app/(testPages)/(apis)/auth/server/page.tsx
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/hooks/queryParams.ts
  src/hooks/useUrlParams.ts
  src/types/api/gatheringApi.d.ts
  src/types/api/reviews.d.ts
Labels: :bug: FIX, :fire:REMOVE, :recycle: REFACTOR

#51 [MNM-35] feat:공통 컴포넌트 calendar
  src/app/(testPages)/calendar/dropdown/page.tsx
  src/app/(testPages)/calendar/page.tsx
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/KakaoMapLayout.tsx
  src/app/groupDetail/_components/Map.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DropdownCalendar.tsx
  src/components/Filter/Dropdown.tsx
  src/components/Filter/FilterButton.tsx
  src/components/Filter/FilterDropDown.tsx
  src/hooks/useClickOutside.ts
  src/store/dateStore.ts
  src/types/components/calendar.d.ts
Labels: :recycle: REFACTOR

#52 [MNM-68]feat: react query 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/providers.tsx
Labels: :sparkles: FEATURE

#53 [MNM-67] refactor:api
  src/apis/HttpClient/HttpClient.ts
  src/apis/HttpClient/retry.ts
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/apis/method/delete.ts
  src/apis/method/get.ts
  src/apis/method/postPut.ts
  src/apis/searchGatheringApi.ts
  src/app/(testPages)/(apis)/auth/page.tsx
  src/app/(testPages)/(apis)/auth/server/page.tsx
  src/app/actions/auth.ts
  src/types/api/authApi.d.ts
  src/types/api/gatheringApi.d.ts
  src/types/components/card.d.ts
  src/types/store/user.d.ts
Labels: :recycle: REFACTOR

#54 [MNM-67] refactor: api
  src/apis/assignGatheringApi.ts
  src/apis/authApi.ts
  src/apis/favoriteGatheringApi.ts
  src/apis/reviewsApi.ts
  src/apis/searchGatheringApi.ts
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/types/api/gatheringApi.d.ts
  src/types/api/reviews.d.ts
Labels: :recycle: REFACTOR

#55 [MNM-69] refactor sign
  src/apis/authApi.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(testPages)/input/page.tsx
  src/utils/schema.ts
Labels: :recycle: REFACTOR, :sparkles: FEATURE

#56 [MNM-74]fix: createAPI 수정
  src/apis/assignGatheringApi.ts
  src/app/(testPages)/(apis)/testgathering/create/page.tsx
  src/app/(testPages)/(apis)/testgathering/page.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#57 [M NM-73] feat: 모임생성
  next.config.mjs
  package-lock.json
  package.json
  src/apis/method/get.ts
  src/apis/method/getMaingPage.ts
  src/app/(home)/[id]/page.tsx
  src/app/(home)/_components/CreateClub.tsx
  src/app/(home)/_components/CreateGathering.tsx
  src/app/(home)/_components/FilterSection.tsx
  src/app/(home)/_components/Gathering.tsx
  src/app/(home)/_components/GatheringSever.tsx
  src/app/(home)/_components/HeroSection.tsx
  src/app/(home)/_components/Input.tsx
  src/app/(home)/_components/SelectedType.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/search/[id]/page.tsx
  src/app/page.tsx
  src/components/Kakaomap/Kakao.tsx
  src/hooks/CreateGathering/fromHandlers.ts
  src/hooks/useUrlParams.ts
  src/types/components/card.d.ts
  src/types/pages/home/Category.d.ts
  src/utils/getQueryClient.ts
Labels: :sparkles: FEATURE

#60 [MNM-78]chore: 프록시 서버로 임시 변경
  next.config.mjs
  src/apis/fetchInstance.ts
Labels: :bug: FIX

#61 [MNM-79]refactor: 로그인시 유저데이터 로컬에 저장
  src/store/userStore.ts
Labels: :recycle: REFACTOR

#62 [MNM-78]chore: nextconfig 원복
  next.config.mjs
  src/apis/fetchInstance.ts
Labels: :package: CHORE

#64 [MNM-80]feat: login & social login
  next.config.mjs
  src/apis/authApi.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/signin/route.ts
Labels: :bug: FIX, :recycle: REFACTOR, :sparkles: FEATURE

#66 [MNM-83]fix: 로그인시 유저데이터 로컬에 저장
  src/apis/HttpClient/HttpClient.ts
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/app/(auth)/signin/page.tsx
  src/app/actions/auth.ts
  src/app/api/auth/signin/route.ts
Labels: :bug: FIX

#67 [MNM-63]refactor: 목데이터 삭제, 카드 컴포넌트 추가
  src/app/reviews/_components/RatingComponent.tsx
  src/app/reviews/_components/ReviewCard.tsx
  src/app/reviews/_components/ReviewListComponent.tsx
  src/components/Filter/FilterDropDown.tsx
  src/types/components/filter.d.ts
Labels: :bug: FIX, :package: CHORE, :fire:REMOVE, :recycle: REFACTOR

#65 [MNM-81] feat: GNB 프로필 드롭다운 기능 추가
  public/icons/magnifier.svg
  src/components/Gnb.tsx
Labels: :sparkles: FEATURE

#74 [MNM-41] feat: 상세페이지 구현
  public/icons/chevron_left.svg
  public/icons/chevron_right.svg
  src/app/globals.css
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/DetailCard.tsx
  src/app/groupDetail/_components/FixedBottomBar.tsx
  src/app/groupDetail/_components/GroupDetail.tsx
  src/app/groupDetail/_components/Map.tsx
  src/app/groupDetail/_components/Reviews.tsx
Labels: :sparkles: FEATURE

#75 [MNM-35] fix: 캘린더 컴포넌트 한국 날짜로 변경
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DropdownCalendar.tsx
Labels: :bug: FIX

#77 [MNM-89]fix: login error 수정
  src/app/api/auth/signin/route.ts
Labels: :bug: FIX

#78 [MNM-87]fix: 메인페이지 Card 시간변경
  public/images/mainPage/ex-images/muckit.svg
  src/app/(home)/_components/Card.tsx
  src/hooks/CreateGathering/fromHandlers.ts
  src/utils/date.ts
Labels: :bug: FIX

#63 [MNM-40] feat: 마이페이지
  next.config.mjs
  public/icons/person.svg
  public/images/modify.svg
  src/apis/reviewsApi.ts
  src/apis/searchGatheringApi.ts
  src/app/mypage/components/mypage/Heart.tsx
  src/app/mypage/components/mypage/Rating.tsx
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/app/mypage/utils/MyReviews.tsx
  src/components/AllReviewCard.tsx
  src/components/MypageCard/MypageCard.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/hooks/useGatherings.ts
  src/hooks/useReviews.ts
  src/hooks/useUserProfile.ts
  src/types/api/authApi.d.ts
  src/types/api/gatheringApi.ts
  src/types/components/card.d.ts
  src/types/components/heart.ts
Labels: :sparkles: FEATURE

#76 [MNM-88]fix: 드롭다운 에러 수정
  src/app/(home)/_components/FilterSection.tsx
  src/app/reviews/_components/ReviewListComponent.tsx
  src/components/Filter/FilterDropDown.tsx
  src/constants/filter.ts
Labels: :bug: FIX

#79 Dev 사항 Main 에 머지
  next.config.mjs
  public/icons/chevron_left.svg
  public/icons/chevron_right.svg
  public/icons/person.svg
  public/images/mainPage/ex-images/muckit.svg
  public/images/modify.svg
  src/apis/reviewsApi.ts
  src/apis/searchGatheringApi.ts
  src/app/(home)/_components/Card.tsx
  src/app/(home)/_components/FilterSection.tsx
  src/app/api/auth/signin/route.ts
  src/app/globals.css
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/DetailCard.tsx
  src/app/groupDetail/_components/FixedBottomBar.tsx
  src/app/groupDetail/_components/GroupDetail.tsx
  src/app/groupDetail/_components/Map.tsx
  src/app/groupDetail/_components/Reviews.tsx
  src/app/mypage/components/mypage/Heart.tsx
  src/app/mypage/components/mypage/Rating.tsx
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/app/mypage/utils/MyReviews.tsx
  src/app/reviews/_components/ReviewListComponent.tsx
  src/components/AllReviewCard.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DropdownCalendar.tsx
  src/components/Filter/FilterDropDown.tsx
  src/components/MypageCard/MypageCard.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/constants/filter.ts
  src/hooks/CreateGathering/fromHandlers.ts
  src/hooks/useGatherings.ts
  src/hooks/useReviews.ts
  src/hooks/useUserProfile.ts
  src/types/api/authApi.d.ts
  src/types/api/gatheringApi.ts
  src/types/components/card.d.ts
  src/types/components/heart.ts
  src/utils/date.ts
Labels: :bug: FIX, :recycle: REFACTOR, :sparkles: FEATURE

#69 [MNM-84]fix: api type
  src/apis/assignGatheringApi.ts
  src/apis/method/getMaingPage.ts
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/FixedBottomBar.tsx
  src/app/groupDetail/_components/GroupDetail.tsx
  src/app/groupDetail/_components/Reviews.tsx
  src/app/layout.tsx
  src/components/MypageCard/MypageCard.tsx
  src/hooks/queryParams.ts
  src/hooks/useUrlParams.ts
  src/types/api/reviews.d.ts
Labels: :bug: FIX, :recycle: REFACTOR, :sparkles: FEATURE

#70 [MNM-85]refactor: token 카멜케이스에서 하이픈으로 변경
  src/apis/HttpClient/HttpClient.ts
  src/apis/authApi.ts
  src/apis/fetchInstance.ts
  src/app/actions/auth.ts
  src/app/api/auth/signin/route.ts
  src/hooks/CreateGathering/fromHandlers.ts
Labels: :recycle: REFACTOR

#84 [MNM-84] fix:api type
  src/apis/HttpClient/HttpClient.ts
  src/apis/HttpClient/error.ts
  src/apis/assignGatheringApi.ts
  src/apis/authApi.ts
  src/apis/favoriteGatheringApi.ts
  src/apis/fetchInstance.ts
  src/apis/fetchWithMiddleware.ts
  src/apis/reviewsApi.ts
  src/apis/searchGatheringApi.ts
  src/app/(testPages)/(apis)/auth/page.tsx
  src/app/(testPages)/(apis)/auth/server/page.tsx
  src/app/(testPages)/(apis)/testReview/page.tsx
  src/app/(testPages)/(apis)/testgathering/create/page.tsx
  src/app/(testPages)/(apis)/testgathering/page.tsx
  src/app/(testPages)/button/page.tsx
  src/app/(testPages)/calendar/dropdown/page.tsx
  src/app/(testPages)/calendar/page.tsx
  src/app/(testPages)/date/page.tsx
  src/app/(testPages)/filter/page.tsx
  src/app/(testPages)/gnb/page.tsx
  src/app/(testPages)/input/page.tsx
  src/app/(testPages)/modal/page.tsx
  src/app/(testPages)/progressbar/page.tsx
  src/app/api/auth/check-email/route.ts
  src/app/api/auth/check-nickName/route.ts
  src/app/api/auth/managed-access-token/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/gatherings/[id]/cancel/route.ts
  src/app/api/gatherings/[id]/favorite/route.ts
  src/app/api/gatherings/[id]/join/route.ts
  src/app/api/gatherings/[id]/leave/route.ts
  src/app/api/gatherings/[id]/participants/route.ts
  src/app/api/gatherings/[id]/recruit/route.ts
  src/app/api/gatherings/[id]/route.ts
  src/app/api/gatherings/favorite/route.ts
  src/app/api/gatherings/joined/route.ts
  src/app/api/gatherings/route.ts
  src/app/api/gatherings/search/route.ts
  src/app/api/my/gathering/route.ts
  src/app/api/reviews/route.ts
  src/app/api/reviews/score/route.ts
  src/app/api/reviews/statistics/route.ts
  src/app/api/user/route.ts
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/app/mypage/utils/MyReviews.tsx
  src/hooks/useGatherings.ts
  src/hooks/useReviews.ts
  src/types/api/gatheringApi.d.ts
  src/types/api/gatheringApi.ts
  tsconfig.json
Labels: :bug: FIX, :recycle: REFACTOR

#85 [MNM-84]fix: 엑세스 토큰없을시 언디파인으로 가던거 수정
  src/app/api/gatherings/[id]/cancel/route.ts
  src/app/api/gatherings/[id]/favorite/route.ts
  src/app/api/gatherings/[id]/join/route.ts
  src/app/api/gatherings/[id]/leave/route.ts
  src/app/api/gatherings/[id]/route.ts
  src/app/api/gatherings/favorite/route.ts
  src/app/api/gatherings/joined/route.ts
  src/app/api/gatherings/route.ts
  src/app/api/my/gathering/route.ts
  src/app/api/reviews/route.ts
  src/app/api/user/route.ts
Labels: :bug: FIX

#86 [MNM-98] refactor: 프로필 드롭다운 닫힘 기능 추가
  src/components/Gnb.tsx
Labels: :recycle: REFACTOR

#88 [MNM-99]feat: 이미지 추가
  public/images/bye.svg
  public/images/lemon_logo.png
  public/images/profile.svg
Labels: :package: CHORE

#87 [MNM-93]refactor: 로그인 및 회원가입 페이지 리팩토링
  public/images/img_login.png
  src/apis/authApi.ts
  src/app/(auth)/_components/PopupComponent.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/check-email/route.ts
  src/app/api/auth/check-nickName/route.ts
Labels: :recycle: REFACTOR

#93 [MNM-97] refactor: mypage card
  public/images/lemonProfile.svg
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/components/MypageCard/ReviewCard.tsx
Labels: :recycle: REFACTOR

#95 [MNM-105]feat: social login
  public/images/vercel.svg
  src/apis/authApi.ts
  src/apis/fetchWithMiddleware.ts
  src/app/(auth)/layout.tsx
  src/app/api/auth/socialSignin/route.ts
  src/app/social/google/page.tsx
  src/app/social/kakao/page.tsx
Labels: :sparkles: FEATURE

#97 FEAT: dev를 main에 merge
  public/images/lemonProfile.svg
  public/images/vercel.svg
  src/apis/authApi.ts
  src/apis/fetchWithMiddleware.ts
  src/app/(auth)/layout.tsx
  src/app/(home)/_components/CreateGathering.tsx
  src/app/(home)/_components/Input.tsx
  src/app/(home)/_components/SelectedType.tsx
  src/app/api/auth/socialSignin/route.ts
  src/app/api/gatherings/route.ts
  src/app/globals.css
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/app/reviews/_components/AllReviews.tsx
  src/app/social/google/page.tsx
  src/app/social/kakao/page.tsx
  src/components/Kakaomap/Kakao.tsx
  src/components/Modal.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/constants/categoryList.ts
  src/hooks/CreateGathering/formHandler.ts
  src/utils/createGathSchema.ts
Labels: :bug: FIX, :recycle: REFACTOR, :sparkles: FEATURE

#98 [MNM-113] feat: 리뷰 작성 점수 주기 기능
  src/app/mypage/components/Heart.tsx
  src/app/mypage/components/Rating.tsx
  src/app/mypage/components/SelectRating.tsx
  src/components/AllReviewCard.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/hooks/useReviews.ts
Labels: :sparkles: FEATURE

#96 [MNM-103] feat: GNB 찜한 목록 개수 표시 기능
  src/components/Button/FavoriteButton.tsx
  src/components/Gnb.tsx
  src/store/userStore.ts
Labels: :sparkles: FEATURE

#100 [MNM-120] refactor: social
  src/app/(home)/_components/GatheringClient.tsx
  src/app/(home)/_components/SelectedType.tsx
  src/app/api/auth/socialSignin/route.ts
  src/app/myFavorite/gathering/_components/FavoriteGathClient.tsx
  src/app/social/google/page.tsx
  src/app/social/kakao/page.tsx
Labels: :bug: FIX

#103 [MNM-116] refactor: GNB 검색바 & 햄버거 버튼
  public/icons/hamburger.svg
  src/components/Gnb.tsx
Labels: :recycle: REFACTOR

#104 [MNM-100] refactor: all review
  src/app/reviews/_components/AllReviews.tsx
  src/app/reviews/_components/ReviewListComponent.tsx
  src/app/reviews/_components/Skeleton/RatingSkeleton.tsx
  src/app/reviews/_components/Skeleton/ReviewCardSkeleton.tsx
  src/app/reviews/layout.tsx
  src/app/reviews/page.tsx
Labels: :recycle: REFACTOR, :sparkles: FEATURE

#105 [MNM-121] refactor signin
  src/apis/authApi.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/signout/route.ts
  src/components/Gnb.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#111 [MNM-127] refactor: GNB 검색바 2개 중 1개 요소 제거
  src/components/Gnb.tsx
Labels: :recycle: REFACTOR

#110 [MNM-126]fix: 모임생성 키워드
  src/__tests__/unit/pages/gatherings/createGath.test.ts
  src/app/(home)/_components/CreateGathering.tsx
  src/utils/formHandler.ts
Labels: :bug: FIX, :sparkles: FEATURE

#115 MNM-133-feat: toast 추가
  src/components/Toast.tsx
  src/store/useToastStore.tsx
Labels: :sparkles: FEATURE

#119 [MNM-122] refactor: mypage
  src/apis/searchGatheringApi.ts
  src/app/api/gatherings/by/[id]/route.ts
  src/app/mypage/components/Skeleton.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/components/MypageCard/MypageCard.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/types/api/gatheringApi.d.ts
  src/types/components/card.d.ts
Labels: :recycle: REFACTOR

#120 [MNM-140]fix: 서치바경로,jest-tsx오류
  .eslintrc.json
  jest.config.js
  jest.config.ts
  next.config.mjs
  package-lock.json
  package.json
  setupTests.ts
  src/__tests__/unit/components/Chip.test.tsx
  src/components/Gnb.tsx
  src/hooks/useUrlParams.ts
  tsconfig.jest.json
  tsconfig.json
Labels: :bug: FIX, :package: CHORE

#112 [MNM-130] fix: api type
  package-lock.json
  src/__tests__/apis/assignGatheringApi.test.ts
  src/__tests__/apis/authApi.test.ts
  src/__tests__/apis/favoriteGatheringApi.test.ts
  src/__tests__/apis/reviewsApi.test.ts
  src/__tests__/apis/searchGatheringsApi.test.ts
  src/apis/assignGatheringApi.ts
  src/apis/authApi.ts
  src/apis/searchGatheringApi.ts
  src/app/api/auth/check-nickname/route.ts
  src/app/api/my/gathering/route.ts
  src/app/groupDetail/_components/EditGathering.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/types/api/gatheringApi.d.ts
Labels: :bug: FIX, :recycle: REFACTOR, :sparkles: FEATURE

#114 [MNM-131]chore: button , input 테스트코드 추가
  src/__tests__/unit/components/button.test.tsx
  src/__tests__/unit/components/input.test.ts
  src/__tests__/unit/components/input.test.tsx
  src/__tests__/unit/components/textArea.test.tsx
Labels: :package: CHORE, :recycle: REFACTOR

#121 [MNM-142]fix: 모임 수정 오류 수정
  src/apis/assignGatheringApi.ts
  src/app/api/gatherings/[id]/route.ts
Labels: :bug: FIX
