Repository FESI5-team9/Frontend, pull requests merged in 2025-01, with the labels that each got.

#124 [MNM-138]feat: meta tag 및 구글 애널리틱스 추가
  src/app/(auth)/layout.tsx
  src/app/(home)/page.tsx
  src/app/(home)/search/[id]/page.tsx
  src/app/actions/auth.ts
  src/app/groupDetail/[id]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/reviews/page.tsx
  src/lib/GoogleAnalytics.tsx
Labels: :recycle: REFACTOR, :sparkles: FEATURE

#126 [MNM-139] refactor: mypage
  src/apis/authApi.ts
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/hooks/useGatherings.ts
  src/types/api/authApi.d.ts
Labels: :bug: FIX, :recycle: REFACTOR

#125 [MNM-143] fix: creategath, readme
  .eslintrc.json
  README.md
  cypress/e2e/GathClient.cy.ts
  src/__tests__/apis/searchGatheringsApi.test.ts
  src/apis/assignGatheringApi.ts
  src/apis/favoriteGatheringApi.ts
  src/app/(home)/_components/ButtonJoin.tsx
  src/app/(home)/_components/Card.tsx
  src/app/(home)/_components/CreateGathering.tsx
  src/components/Button/FavoriteButton.tsx
  src/components/Toast.tsx
  src/mocks/GathClient.ts
  src/store/useToastStore.ts
  tsconfig.json
Labels: :bug: FIX, :sparkles: FEATURE

#128 [MNM-41] refactor: 상세페이지 리팩토링
  src/apis/assignGatheringApi.ts
  src/app/groupDetail/_components/DetailCard.tsx
  src/app/groupDetail/_components/EditGathering.tsx
  src/app/groupDetail/_components/FixedBottomBar.tsx
  src/app/groupDetail/_components/GroupDetail.tsx
  src/components/Toast.tsx
Labels: :recycle: REFACTOR

#131 [MNM-147] refactor: all reviews
  src/app/reviews/_components/AllReviews.tsx
  src/app/reviews/_components/ReviewCard.tsx
Labels: :recycle: REFACTOR, :sparkles: FEATURE

#130 [MNM-145] refactor: mypage
  cypress/support/component-index.html
  cypress/support/component.ts
  src/apis/assignGatheringApi.ts
  src/app/api/gatherings/[id]/leave/route.ts
  src/app/api/gatherings/[id]/recruit/route.ts
  src/app/api/user/route.ts
  src/app/mypage/page.tsx
  src/app/mypage/utils/MyCreatedGathering.tsx
  src/app/mypage/utils/MyGathering.tsx
  src/components/MypageCard/MypageCard.tsx
  src/components/MypageCard/ReviewCard.tsx
  src/components/Toast.tsx
  src/hooks/useReviews.ts
Labels: :recycle: REFACTOR

#133 [MNM-149] refactor: GNB style
  src/components/Gnb.tsx
Labels: :lipstick: STYLE

#143 [MNM-148] feat: 필터 컴포넌트 테스트
  src/__tests__/unit/components/filters.test.tsx
  src/app/groupDetail/[id]/page.tsx
  src/app/groupDetail/_components/DetailCard.tsx
  src/app/groupDetail/_components/EditGathering.tsx
  src/app/groupDetail/_components/FixedBottomBar.tsx
  src/app/groupDetail/_components/GroupDetail.tsx
  src/app/groupDetail/_components/Map.tsx
  src/app/groupDetail/_components/ReviewRatingComponent.tsx
  src/app/groupDetail/_components/Reviews.tsx
  src/app/groupDetail/_components/Skeleton/ReviewRatingSkeleton.tsx
  src/components/Button/FavoriteButton.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DropdownCalendar.tsx
  src/components/Filter/Dropdown.tsx
  src/components/Filter/FilterButton.tsx
  src/components/Filter/FilterDropDown.tsx
  src/components/Gnb.tsx
  src/types/components/filter.d.ts
Labels: :sparkles: FEATURE
